generated
scanForTokenX5
	self recordMatch: #(109).
	self step.
	currentCharacter isDigit
		ifTrue: [ [ self recordMatch: #(109).
			self step.
			currentCharacter isDigit ] whileTrue.
			^ self reportLastMatch ].
	('Xx' includes: currentCharacter)
		ifTrue: [ self step.
			(currentCharacter isDigit
				or: [ (currentCharacter between: $A and: $F)
						or: [ currentCharacter between: $a and: $f ] ])
				ifTrue: [ [ self recordMatch: #(110).
					self step.
					currentCharacter isDigit
						or: [ (currentCharacter between: $A and: $F)
								or: [ currentCharacter between: $a and: $f ] ] ] whileTrue ] ].
	^ self reportLastMatch