tests - contracts
testSimpleContractSubcurrencyExample
	"Simple contract example (Subcurrency subsection) found in the solidity web site. The example was modified because they used the 'from' which is a keyword as an identifier
	https://solidity.readthedocs.io/en/develop/introduction-to-smart-contracts.html"
	self parseTest: 
'pragma solidity ^0.4.0;

contract Coin {
    // The keyword "public" makes those variables
    // readable from outside.
    address public minter;
    mapping (address => uint) public balances;

    // Events allow light clients to react on
    // changes efficiently.
    event Sent(address from1, address to, uint amount);

    // This is the constructor whose code is
    // run only when the contract is created.
    function Coin() {
        minter = msg.sender;
    }

    function mint(address receiver, uint amount) {
        if (msg.sender != minter) return;
        balances[receiver] += amount;
    }

    function send(address receiver, uint amount) {
        if (balances[msg.sender] < amount) return;
        balances[msg.sender] -= amount;
        balances[receiver] += amount;
        Sent(msg.sender, receiver, amount);
    }
}'.