generated-reduction actions
reduceActionFor__TypeName__type____ModifierStorage__storage_modifier______LiteralIdentifier__identifier__________TypeName__type____ModifierStorage__storage_modifier______LiteralIdentifier__identifier_______1: nodes
	| result |
	result := Array new: 4.
	result at: 1 put: (OrderedCollection new: 2).
	result at: 2 put: (OrderedCollection new: 2).
	result at: 3 put: (OrderedCollection new: 2).
	result at: 4 put: (OrderedCollection new: 2).
	^ result